version: "3.9"
services:
  mockserver:
    image: mockserver/mockserver
    ports:
      - '1080:1080'

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: rabbitmq-test
    ports:
      - '15672:15672'
    volumes:
      - .data/rabbitmq:/var/lib/rabbitmq
