name: docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}

          # GITHUB_TOKEN works for `master` but not PR
          # using PAT here to workaround that
          # see https://github.community/t/403-error-on-container-registry-push-from-github-action/173071
          password: ${{ secrets.GH_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  e2e:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}

    services:
      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - '15672:15672'

    steps:
      - run: node dist/index.js
        env:
          AMQP_FETCH_CONNECT_URL: amqp://rabbitmq
