on:
  push:
    branches:
      - master
  pull_request:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:lts-alpine

    services:
      mockserver:
        image: mockserver/mockserver
        ports:
          - '1080:1080'

      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - '15672:15672'

    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run test:coverage
        env:
          INTEGRATION_CONNECT_URL: amqp://rabbitmq
          INTEGRATION_MOCKSERVER_HOST: mockserver
      - uses: codecov/codecov-action@v1
